---
- name: Using when with facts
  hosts: node0
  tasks:
    - name: Detect CentOS Servers
      debug:
         msg: "This is a CentOS Server."
      when: ansible_facts['distribution'] == "CentOS"
