
---
- name : loop example playbook
  hosts: node0
  tasks:
   - name: Print message
     debug:
       msg: "The item is {{ item }} and loop index is {{ i }}"
     loop:
      - hello
      - kaoutar
      - Sabri
     loop_control:
        index_var: i
