---
- name: all in one playbook
  hosts: node0
  tasks:
    #Install packages
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mariadb
        - php
      when: ansible_facts['distribution'] == "CentOS"

   # Create user 
    - name: Create new user
      user:
       name: student
       password: "{{ 'mypassword' | password_hash('sha512') }}"
