---
- name: First play
  hosts: node0
  become: yes
  tasks:
   - name: latest Apache Version
     yum:
       name: httpd
       state: latest

- name: Second play
  hosts: node0
  tasks:
    - name: install git
      yum:
        name: git
        state: present
