---
- name: show some facts
  hosts: node0
  tasks:
    - name: display node0 ipv4 address
      debug:
        msg: IPv4 address is {{ ansible_facts.default_ipv4.address }}
    - name: display node0 fqdn
      debug:
        msg: FQDN is {{ ansible_facts.fqdn }}
    - name: display node0 OS distribution
      debug:
         msg: OS Distro is {{ ansible_facts.distribution }}
