---
- name: Working with variables
  hosts: all
  vars: 
    port_nums: [21,22,23,25,80]
    
    users: 
      admin1:
         username: kaoutar
         uid: 1000
         shell: /bin/bash
      admin2:
         username: sabri
         uid: 1001
         shell: /bin/bash 
  tasks:
     - name: Show 2nd item in port_nums
       debug:
         msg: SSH port ={{port-nums[1]}}

     - name : Show uid of kaoutar
       debug:
          msg: uid of kaoutar is {{users.admin1.uid}}       
